language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r dev.requirements.txt
script:
  - coverage run -m unittest && coverage report
  - bash <(curl -s https://codecov.io/bash)
  - cd docs && make html
branches:
  only:
  - master
  - develop